name: Lint & Build the model

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: necko-actions/setup-smithy@0e280f9054dbc6f23406e98235c5e18f1d2e4dd7 # v1
        with:
          version: "1.40.0"
      - run: smithy validate model/
      - run: smithy format model/
      - run: git diff --exit-code
      - run: smithy diff --mode git --old origin/main --logging INFO
      - run: smithy build model/
